### ISSUE TITLE
[Bug] wifi is unstable

### ISSUE THREAD

**Issue by nikdib** [MartinX3-AndroidDevelopment-LineageOS/bug_tracker#5] opened 2020-02-04 10:46 UTC
**Platform:** TAMA
**Device:** AKARI, APOLLO, AKATSUKI (xz2c h8314)
**Kernel version:** 4.14
**Android version:** 10.0

**Description**
randomly the wifi disconnects and reconnects after maybe 1 minutes

**Symptoms**
it's random

**How to reproduce**
i can't reproduce it but just wait

**Additional context**
i take a log with an app (alogcat root) while the bug was happening. I don't know if it's helpful for you.
[alogcat.2020-02-04-11-36-51+0100.txt](https://github.com/MartinX3-AndroidDevelopment-LineageOS/bug_tracker/files/4152782/alogcat.2020-02-04-11-36-51%2B0100.txt)

**Comment by MartinX3** [comment] 2020-02-04 11:01
Thanks for your report

Duplicate of https://github.com/MartinX3-AndroidDevelopment-LineageOS/bug_tracker/issues/3

**Closed as completed by MartinX3** 2020-02-04 11:01 UTC
Labels: bug
