### ISSUE TITLE
[Bug] battery level is bugged

### ISSUE THREAD

**Issue by nikdib** [MartinX3-AndroidDevelopment-LineageOS/bug_tracker#6] opened 2020-02-04 11:02 UTC
**Platform:** TAMA
**Device:** AKARI, APOLLO, AKATSUKI (xz2c h8314)
**Kernel version:** 4.14
**Android version:** 10.0

**Description**
while using the phone the battery went down to 33% but then it never went down and I restarted 2 times. So I attached the charger and in 1 minute it went from 33% to 41 and it kept going up fast. but now there seems to be no bug momentarily... i will check

**Symptoms**
Write the symptoms here.

**How to reproduce**
I can't reproduce

**Additional context**
i have a screenshot but it doesn't help. in the circled part it was always charging and you can see that the battery even went down.
![Screenshot_20200204-110151_Impostazioni](https://user-images.githubusercontent.com/60649691/73739308-3faff380-4746-11ea-86f0-67e8c6a3c167.png)

**Comment by MartinX3** [comment] 2020-02-04 11:07
Thank you for your report

Duplicate of https://github.com/MartinX3-AndroidDevelopment-LineageOS/bug_tracker/issues/2

**Closed as completed by MartinX3** 2020-02-04 11:07 UTC
Labels: bug
